centers:
  - name: ""
    secretKey: ""
    url: ""

mongodb:
  uri: "mongodb://localhost:27017"
  database: "db"

duckdb:
  path: "./data/monitor.db"

monitor:
  fetch_interval_days: 30
  check_interval_days: 7
  http_timeout_secs: 15
  max_concurrent: 32
  retry_times: 1
